package com.comp2042.input;

/**
 * Source of an input event.
 *
 * <p>Distinguishes between inputs generated by the user (keyboard/mouse)
 * and those generated programmatically by a thread (e.g. automated replay
 * or AI). Helper predicates are provided for convenience.
 */
public enum EventSource {
    /** Event originated from a human user. */
    USER,

    /** Event originated from a background thread or programmatic source. */
    THREAD;

    /**
     * @return {@code true} when this source represents a user-generated event
     */
    public boolean isUser() {
        return this == USER;
    }

    /**
     * @return {@code true} when this source represents a thread/programmatic event
     */
    public boolean isThread() {
        return this == THREAD;
    }

    /**
     * Parse an {@code EventSource} from a case-insensitive name. Returns
     * {@code null} for unknown or null inputs.
     */
    public static EventSource fromName(String name) {
        if (name == null) return null;
        try {
            return valueOf(name.trim().toUpperCase());
        } catch (IllegalArgumentException ex) {
            return null;
        }
    }
}
